name: techtrack_ai
description: TechTrack AI mobile app for roadmap learning, daily tasks, AI mentor, progress, and gamification.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  firebase_messaging: ^15.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
